### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by acostroma** [peterdemin/snmp-formula-rpm#1]
Run failed on minions: client2-daemon 
Failures: 
   client2-daemon: 
       Data failed to compile: 

---

```
   Specified SLS snmp.conf in saltenv base is not available on the salt master or through a configured fileserver
```

What's the real reason? It crashes sometimes on real hardware only on some nodes. Any other nodes deployed successfully.

**Comment by peterdemin** [comment]
Alexey, hi. I believe you should repost this question to snmp-formula since error has nothing to do with rpm packaging and no one else except me monitors this repo.
Also it could be helpful if you post the command that failed and recursive listing of SNMP formula directory deployed on falling node.
